# app/utils/pdf_generator.py

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, cm
from reportlab.graphics.shapes import Drawing, Circle, String
from reportlab.graphics import renderPDF
from io import BytesIO
from datetime import datetime
import hashlib

def draw_digital_stamp(canvas, x, y):
    """Draws a vector-based 'Official Stamp' on the PDF"""
    canvas.saveState()
    canvas.setStrokeColor(colors.darkblue)
    canvas.setLineWidth(2)
    
    # Outer Circle
    canvas.circle(x, y, 40, stroke=1, fill=0)
    # Inner Circle
    canvas.setLineWidth(1)
    canvas.circle(x, y, 35, stroke=1, fill=0)
    
    # Text inside stamp
    canvas.setFont("Helvetica-Bold", 8)
    canvas.setFillColor(colors.darkblue)
    canvas.drawCentredString(x, y + 25, "FLEET MANAGEMENT")
    canvas.drawCentredString(x, y - 28, "OFFICIAL APPROVAL")
    
    # Date
    canvas.setFont("Helvetica-Bold", 10)
    canvas.setFillColor(colors.red)
    canvas.drawCentredString(x, y - 3, "APPROVED")
    
    date_str = datetime.now().strftime("%d/%m/%Y")
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.black)
    canvas.drawCentredString(x, y - 12, date_str)
    
    canvas.restoreState()

def generate_mission_order_pdf(request, approver_name, passenger_details):
    """
    Generates an official Mission Order PDF.
    passenger_details: List of User objects (from DB) corresponding to matricules.
    """
    buffer = BytesIO()
    
    # Define a custom page creation function to allow absolute positioning (for the stamp)
    def add_header_footer_stamp(canvas, doc):
        canvas.saveState()
        
        # 1. Header Line
        canvas.setLineWidth(2)
        canvas.setStrokeColor(colors.darkblue)
        canvas.line(0.5 * inch, 10.8 * inch, 7.8 * inch, 10.8 * inch)
        
        # 2. Watermark (Optional, light grey)
        canvas.setFont("Helvetica-Bold", 60)
        canvas.setFillColorRGB(0.9, 0.9, 0.9)
        canvas.saveState()
        canvas.translate(4 * inch, 5 * inch)
        canvas.rotate(45)
        canvas.drawCentredString(0, 0, "OFFICIAL MISSION")
        canvas.restoreState()
        
        # 3. Footer
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.gray)
        canvas.drawString(0.5 * inch, 0.5 * inch, f"Generated by FleetDash System | ID: {request.id} | {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        canvas.drawRightString(7.8 * inch, 0.5 * inch, f"Page {doc.page}")
        
        canvas.restoreState()

    doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=40, leftMargin=40, topMargin=60, bottomMargin=40)
    elements = []
    styles = getSampleStyleSheet()

    # --- TITLE ---
    title_style = ParagraphStyle('Title', parent=styles['Heading1'], fontSize=20, alignment=1, spaceAfter=10, textColor=colors.darkblue)
    elements.append(Paragraph("ORDRE DE MISSION / MISSION ORDER", title_style))
    elements.append(Paragraph(f"<b>Reference:</b> REQ-{datetime.now().year}-{request.id:05d}", styles['Normal']))
    elements.append(Spacer(1, 20))

    # --- MISSION DETAILS ---
    elements.append(Paragraph("1. Mission Details", styles['Heading3']))
    
    fmt = "%d %b %Y, %H:%M"
    dep_str = request.departure_time.strftime(fmt) if request.departure_time else "N/A"
    ret_str = request.return_time.strftime(fmt) if request.return_time else "N/A"
    requester_name = request.requester.full_name if request.requester else "Unknown"
    dept_name = request.requester.service.service_name if (request.requester and request.requester.service) else "N/A"

    data = [
        ["Mission ID", f"#{request.id}"],
        ["Requester", requester_name],
        ["Department / Service", dept_name],
        ["Destination", request.destination],
        ["Departure Date", dep_str],
        ["Return Date", ret_str],
        ["Vehicle", request.vehicle.plate_number if request.vehicle else "Not Assigned"],
        ["Driver", request.driver.full_name if request.driver else "Self-Driven"],
        ["Purpose", request.description or "Administrative Mission"]
    ]

    t = Table(data, colWidths=[2.5 * inch, 4 * inch])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.aliceblue),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'), # First col bold
        ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 20))

    # --- PASSENGER MANIFEST ---
    elements.append(Paragraph("2. Passenger Manifest", styles['Heading3']))
    
    # Table Header
    pass_data = [["#", "Matricule", "Full Name", "Agency", "Service", "Role"]]
    
    # Populate Table with RICH data from the DB objects
    if passenger_details:
        for idx, user in enumerate(passenger_details, 1):
            agency = user.agency.agency_name if user.agency else "-"
            service = user.service.service_name if user.service else "-"
            role = user.role.name if user.role else "-"
            pass_data.append([
                str(idx), 
                user.matricule, 
                user.full_name, 
                agency, 
                service, 
                role
            ])
    else:
        pass_data.append(["-", "-", "No additional passengers", "-", "-", "-"])

    # Define column widths for passenger table
    col_widths = [0.4*inch, 1.0*inch, 1.8*inch, 1.2*inch, 1.2*inch, 1.0*inch]
    
    t_pass = Table(pass_data, colWidths=col_widths)
    t_pass.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.darkblue), # Header bg
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),     # Header text
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.black),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.whitesmoke])
    ]))
    elements.append(t_pass)
    elements.append(Spacer(1, 30))

    # --- SIGNATURE BLOCK ---
    elements.append(Paragraph("3. Authorization", styles['Heading3']))
    
    # Generate a "Digital Hash" for the signature
    sig_hash = hashlib.sha256(f"{request.id}{approver_name}{datetime.now()}".encode()).hexdigest()[:16].upper()
    
    # Signature Table (Left: Text, Right: Space for Stamp)
    sig_data = [[
        f"""
        <b>Status:</b> FULLY APPROVED
        <br/><b>Approved By:</b> {approver_name}
        <br/><b>Date:</b> {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
        <br/><b>Digital Signature ID:</b> <font color="blue">{sig_hash}</font>
        <br/><br/>
        <i>This document is digitally signed and valid without a physical signature.</i>
        """,
        "" # Placeholder for stamp
    ]]
    
    t_sig = Table(sig_data, colWidths=[4 * inch, 2.5 * inch])
    t_sig.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('BOX', (0, 0), (-1, -1), 1, colors.black),
        ('BACKGROUND', (0, 0), (-1, -1), colors.white),
    ]))
    elements.append(t_sig)

    # Function to draw the stamp on the PDF after elements are placed
    def on_page_end(canvas, doc):
        add_header_footer_stamp(canvas, doc)
        # Draw stamp roughly where the second column of the signature table is
        # Coordinates need to be estimated or calculated. 
        # For simplicity in reportlab flowables, we usually draw absolute or use a Flowable.
        # Here we draw absolute at bottom right of the content area.
        draw_digital_stamp(canvas, 6.5 * inch, 3.0 * inch)

    doc.build(elements, onFirstPage=on_page_end, onLaterPages=on_page_end)
    buffer.seek(0)
    return buffer