"""Update request model

Revision ID: 383933affee8
Revises: 
Create Date: 2025-12-12 07:56:27.600612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '383933affee8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_requests', sa.Column('passengers', sa.JSON(), nullable=True))
    op.add_column('vehicle_requests', sa.Column('rejection_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_requests', 'rejection_reason')
    op.drop_column('vehicle_requests', 'passengers')
    # ### end Alembic commands ###
